# Generated by Django 4.2 on 2024-02-10 15:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profaile_virefayd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profaile',
            name='Npassport',
            field=models.CharField(default='000000000', max_length=9, verbose_name='passport number'),
        ),
        migrations.AddField(
            model_name='profaile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profaile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
