# Generated by Django 4.2 on 2024-02-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profaile_npassport_profaile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profaile',
        ),
    ]
