# Generated by Django 4.2 on 2024-02-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='Certafica',
            field=models.FileField(default='', upload_to='Certafica_File/'),
        ),
        migrations.AddField(
            model_name='command',
            name='contrat',
            field=models.FileField(default='', upload_to='contrat_File/'),
        ),
        migrations.AddField(
            model_name='command',
            name='passport',
            field=models.FileField(default='', upload_to='Paasport_File/'),
        ),
        migrations.AddField(
            model_name='command',
            name='talonImage',
            field=models.ImageField(default='', upload_to='talon_images/'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercommand', to=settings.AUTH_USER_MODEL),
        ),
    ]
