# Generated by Django 4.2 on 2024-02-17 10:11

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_command_certafica_command_contrat_command_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Certafica',
            field=models.FileField(upload_to='Certafica_File', verbose_name='Latest education certificate '),
        ),
        migrations.AlterField(
            model_name='command',
            name='contrat',
            field=models.FileField(upload_to='contrat_File', verbose_name='The service contract after signing and filling it out '),
        ),
        migrations.AlterField(
            model_name='command',
            name='country',
            field=django_countries.fields.CountryField(default='DZ', max_length=2, verbose_name='Choose your country '),
        ),
        migrations.AlterField(
            model_name='command',
            name='dateOfBirth',
            field=models.DateField(verbose_name='Date of birth '),
        ),
        migrations.AlterField(
            model_name='command',
            name='nPassport',
            field=models.IntegerField(verbose_name='The serial number of your passport '),
        ),
        migrations.AlterField(
            model_name='command',
            name='passport',
            field=models.FileField(upload_to='Paasport_File', verbose_name='Your Passport '),
        ),
        migrations.AlterField(
            model_name='command',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='command',
            name='talonImage',
            field=models.ImageField(upload_to='talon_images', verbose_name='A Picture of the payment receipt '),
        ),
    ]
